# Generated by Django 5.0.6 on 2024-05-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mail', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameModel(
            old_name='Login',
            new_name='SignIn',
        ),
        migrations.RenameField(
            model_name='signin',
            old_name='username',
            new_name='mail',
        ),
    ]
