# Generated by Django 5.0.6 on 2024-05-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_signup_rename_login_signin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='name',
            new_name='usernname',
        ),
        migrations.AlterField(
            model_name='signup',
            name='mail',
            field=models.CharField(max_length=250),
        ),
    ]
