# Generated by Django 5.0.3 on 2024-05-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voiture',
            options={'ordering': ['prix'], 'verbose_name': 'Voiture'},
        ),
        migrations.AddField(
            model_name='voiture',
            name='prix',
            field=models.BigIntegerField(default=0),
        ),
    ]
