# Generated by Django 5.0.3 on 2024-05-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_alter_voiture_options_voiture_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='image',
            field=models.ImageField(default='', upload_to='PhotoDeVoiture/%y/%m/%d'),
        ),
    ]
