# Generated by Django 5.0.3 on 2024-05-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_voiture_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.ImageField(default='', upload_to='PhotoDeVoiture/%y/%m/%d')),
                ('exist', models.BooleanField(default=True)),
                ('prix', models.BigIntegerField(default=0)),
                ('category', models.CharField(choices=[('voiture', 'voiture'), ('moto', 'moto')], max_length=50)),
            ],
            options={
                'verbose_name': 'vehicule',
                'ordering': ['prix'],
            },
        ),
        migrations.DeleteModel(
            name='Voiture',
        ),
    ]
