# Generated by Django 5.0.6 on 2024-05-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=100)),
                ('name', models.TextField()),
                ('image', models.ImageField(default='', upload_to='PhotoDeVoiture/%y/%m/%d')),
                ('exist', models.BooleanField(default=True)),
                ('prix', models.BigIntegerField(default=0)),
                ('typ', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('voiture', 'voiture'), ('moto', 'moto')], max_length=50)),
            ],
            options={
                'verbose_name': 'vehicule',
                'ordering': ['prix'],
            },
        ),
        migrations.DeleteModel(
            name='ListeProduit',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
